import os
import re

configfile: "config.yaml"

input_dir = config["input_dir"]

samples = [
    re.sub(r"\.fastq\.gz$", "", file)
    for file in os.listdir(input_dir)
    if file.endswith(".fastq.gz")
]

rule all:
    input:
        f"{input_dir}/MQC/multiqc_report.html"

rule fastqc:
    input:
        "{input_dir}/{sample}.fastq.gz"
    output:
        "{input_dir}/FQC/{sample}_fastqc.html",
        "{input_dir}/FQC/{sample}_fastqc.zip"
    params:
        input_dir=input_dir
    shell:
        "mkdir -p {params.input_dir}/FQC && fastqc --extract -t 2 -o {params.input_dir}/FQC {input}"

rule multiqc:
    input:
        expand("{dir}/FQC/{sample}_fastqc.zip", dir=input_dir, sample=samples)
    output:
        f"{input_dir}/MQC/multiqc_report.html"
    params:
        input_dir=input_dir
    shell: 
        "mkdir -p {input_dir}/MQC && multiqc {input} -o {params.input_dir}/MQC"
