input_dir: sample_data
fasta: Manta/GCA_000001405.15_GRCh38_full_plus_hs38d1_analysis_set.fna
bed: Manta/hg38.hipstr_reference.bed

###EHDN
EHDN_script: ~/EHdn/scripts

###HipSTR
HipSTR_script: ~/HipSTR/scripts/filter_vcf.py
split_bed: 8

###Stretch
#Relative path of STRetch environment
stretch_env: ../../STRetch/environment.yml
decoy_script: ~/STRetch/scripts/decoy_STR.py
sort_script: ~/STRetch/scripts/sort_fasta.py
