import os
import re

configfile:"config.yaml"

input_dir = config["input_dir"]
fasta = config["fasta"]

samples = [
    re.sub(r"\.cram$", "", file)
    for file in os.listdir(input_dir)
    if file.endswith(".cram")
]

rule all:
    input:
        expand("results/EHdn/str-profiles/{sample}.str_profile.json", sample=samples)


rule EHdn_STR_profile:
    input:
        lambda wildcards: f"{input_dir}/{wildcards.sample}.cram"
    output:
        "results/EHdn/str-profiles/{sample}.str_profile.json"
    params:
        input_dir=input_dir,
        fasta=fasta
    shell: "mkdir -p results && \
        ExpansionHunterDenovo profile \
        --reads {input} \
        --reference {params.fasta} \
        --output-prefix results/EHdn/str-profiles/{wildcards.sample} \
        --min-anchor-mapq 50 \
        --max-irr-mapq 40"
